app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
#Rest (FOSRestBundle)
avrequest:
    type: rest
    resource: AppBundle\Controller\AvRequestRestController
    prefix: /api/
    
booksearchrequest:
    type: rest
    resource: AppBundle\Controller\BookSearchRequestRestController
    prefix: /api/
    
departmentstaff:
    type: rest
    resource: AppBundle\Controller\DepartmentStaffRestController
    prefix: /api/
    
feedback:
    type: rest
    resource: AppBundle\Controller\FeedbackRestController
    prefix: /api/
    
hours:
    type: rest
    resource: AppBundle\Controller\HoursRestController
    prefix: /api/
    

